export ZSH="/home/okitoxo/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git zsh-nvm)

source $ZSH/oh-my-zsh.sh

# Alias
alias gcode='cd ~/Code'
alias gvtex='cd ~/Code/globant/FrontEnd-VTEX'
alias v='nvim'
